### ISSUE TITLE
Add "msgpack.org[nim]" to repo description to publish msgpack-nim to msgpack.org

### ISSUE THREAD

**Issue by vzvu3k6k** [akiradeveloper/msgpack-nim#1]
> あとは, MessagePackの公式にリストされることも目標にして開発を進めていく(何を満たせばいいのか全くわからない).
> [(msgpack-nim report) 実装完了 - テストステ論](http://akiradeveloper.hatenadiary.com/entry/2015/03/01/223654)

The list of msgpack implementations on msgpack.org is generated automatically by crawling.

Check [msgpack/website · GitHub](https://github.com/msgpack/website#publishing-your-msgpack-implementation-to-msgpackorg) for details.

**Comment by akiradeveloper** [comment]
Thanks for your help. Done.
