### ISSUE TITLE
Type mismatch with Nim 0.18.0

### ISSUE THREAD

**Issue by FedericoCeratto** [akiradeveloper/msgpack-nim#11]
Msgpack cannot be used from Nim 0.18.0

Error: type mismatch: got <tuple[buf: PackBuf]> but expected 'Packer = ref Packer:ObjectType'

To reproduce:
```
echo "import msgpack" > foo.nim && nim c foo.nim
```

**Comment by majj** [comment]
the same issue in Nim 0.18.1

**Comment by akiradeveloper** [comment]
fixed with Nim 1.0.0
